INSERT INTO Category (id_category, name_category) VALUES (1, 'masculino');
INSERT INTO Category (id_category, name_category) VALUES (2, 'feminino');
INSERT INTO Category (id_category, name_category) VALUES (3, 'unissex');

INSERT INTO PRODUCT ( ID_PRODUCT, NAME_PRODUCT,  PRICE_PRODUCT, CATEGORY_FK) VALUES (1, 'CALÇA MASCULINA', 50.0, 1);
INSERT INTO PRODUCT ( ID_PRODUCT, NAME_PRODUCT,  PRICE_PRODUCT, CATEGORY_FK) VALUES (2, 'CALÇA FEMININA', 50.0, 2);
INSERT INTO PRODUCT ( ID_PRODUCT, NAME_PRODUCT,  PRICE_PRODUCT, CATEGORY_FK) VALUES (3, 'CALÇA UNISSEX', 50.0, 3)